### ISSUE TITLE
RuntimeError: Cuda error: 2[cudaGraphicsGLRegisterBuffer(&s.cudaPosBuffer, s.glPosBuffer, cudaGraphicsRegisterFlagsWriteDiscard);]

### ISSUE THREAD

**Issue by eragondr** [huanngzh/MV-Adapter#58]
i try to genarate  text to texture and i get this error : 

>  RuntimeError: Cuda error: 2[cudaGraphicsGLRegisterBuffer(&s.cudaPosBuffer, s.glPosBuffer, cudaGraphicsRegisterFlagsWriteDiscard);]

Cuda 12.4
GTX 4090 24gb

here is the log : 
`TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].

100%|██████████| 50/50 [00:23<00:00,  2.17it/s]
[Open3D INFO] actual parallel_partitions 44
/home/eragon/projects/python/AI/LocknessAI/MV_Adapter/mvadapter/utils/mesh_utils/mesh_process.py:293: UserWarning:

The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:203.)

No view mask provided for UV blending, using all valid pixels
Traceback (most recent call last):
  File "/home/eragon/projects/python/AI/LocknessAI/MV_Adapter/scripts/texture_t2tex.py", line 85, in <module>
    out = texture_pipe(
  File "/home/eragon/projects/python/AI/LocknessAI/MV_Adapter/mvadapter/pipelines/pipeline_texture.py", line 347, in __call__
    uv_proj, uv_valid_mask = self.view_inpaint(
  File "/home/eragon/projects/python/AI/LocknessAI/MV_Adapter/mvadapter/pipelines/pipeline_texture.py", line 122, in view_inpaint
    return self.smart_painter(
  File "/home/eragon/projects/python/AI/LocknessAI/MV_Adapter/mvadapter/utils/mesh_utils/smart_paint.py", line 102, in __call__
    render_out = render(
  File "/home/eragon/projects/python/AI/LocknessAI/MV_Adapter/mvadapter/utils/mesh_utils/render.py", line 241, in render
    rast, _ = ctx.rasterize(v_pos_clip, mesh.t_pos_idx, (height, width), grad_db=True)
  File "/home/eragon/projects/python/AI/LocknessAI/MV_Adapter/mvadapter/utils/mesh_utils/render.py", line 55, in rasterize
    return dr.rasterize(
  File "/home/eragon/miniconda3/envs/lockness/lib/python3.10/site-packages/nvdiffrast/torch/ops.py", line 317, in rasterize
    return _rasterize_func.apply(glctx, pos, tri, resolution, ranges, grad_db, -1)
  File "/home/eragon/miniconda3/envs/lockness/lib/python3.10/site-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/eragon/miniconda3/envs/lockness/lib/python3.10/site-packages/nvdiffrast/torch/ops.py", line 253, in forward
    out, out_db = _get_plugin(gl=True).rasterize_fwd_gl(raster_ctx.cpp_wrapper, pos, tri, resolution, ranges, peeling_idx)
RuntimeError: Cuda error: 2[cudaGraphicsGLRegisterBuffer(&s.cudaPosBuffer, s.glPosBuffer, cudaGraphicsRegisterFlagsWriteDiscard);]`

**Comment by Hamad-exarta** [comment]
Are you running this on WSL (Windows)?
This has to do with the openGL drivers and cuda compatibility on WSL.

I solved it by resetting the environment with basic installation and making a code change to make nvdiffrast work with cuda context.

**Comment by eragondr** [comment]
Iam running on Ubutu 22.04.
What you mean "resetting the environment" ? . is that mean i need to create a new environment and install everything again bro ?

**Comment by Hamad-exarta** [comment]
i uninstalled the open GL libraries libegl1-mesa-dev libgles2-mesa-dev  , re installed and check if the nvidia cuda driver is being used by glxinfo | grep "OpenGL renderer"  and openGL version glxinfo | grep "OpenGL version"
Then i changed the file mvadapter/utils/mesh_utils/render.py   , replace the code 
class NVDiffRastContextWrapper:
    def __init__(self, device: str, context_type: str = "gl"):
        self.ctx = dr.RasterizeCudaContext(device=device)
        # if context_type == "gl":
        #     self.ctx = dr.RasterizeGLContext(device=device)
        # elif context_type == "cuda":
        #     self.ctx = dr.RasterizeCudaContext(device=device)
        # else:
        #     raise NotImplementedError


Basically comment the code that uses the GLContext and use CudaContext
self.ctx = dr.RasterizeCudaContext(device=device)   , this force CUDA context usage for nvdiffrast
